#
# Build
#

set build_components {
	core init
	drivers/timer
	drivers/input/ps2
	test/input
        drivers/acpi
        drivers/pci
}


build $build_components

create_boot_directory

#
# Generate config
#

append config {
<config>
	<parent-provides>
		<service name="ROM"/>
		<service name="RAM"/>
		<service name="IRQ"/>
		<service name="IO_MEM"/>
		<service name="IO_PORT"/>
		<service name="CAP"/>
		<service name="PD"/>
		<service name="RM"/>
		<service name="CPU"/>
		<service name="LOG"/>
		<service name="SIGNAL" />
	</parent-provides>
	<default-route>
		<any-service> <parent/> <any-child/> </any-service>
	</default-route>}



append config {
	<start name="acpi">
		<resource name="RAM" quantum="8M"/>
		<binary name="acpi_drv"/>
		<provides>
			<service name="PCI"/>
			<service name="IRQ" />
		</provides>
		<route>
			<service name="PCI"> <any-child /> </service>
			<any-service> <parent/> <any-child /> </any-service>
		</route>
	</start>}

append config {
	<start name="timer">
		<resource name="RAM" quantum="1M"/>
		<provides><service name="Timer"/></provides>
		 <route>
		    <service name="IRQ"><child name="acpi" /></service>
		    <any-service> <parent /> <any-child /></any-service>
		 </route>
	</start>
	<start name="ps2_drv">
		<resource name="RAM" quantum="2M"/>
		<provides><service name="Input"/></provides>
	</start>
	<start name="test-input">
		<resource name="RAM" quantum="1M"/>
	</start>
</config>}

install_config $config

#
# Boot modules
#

# generic modules
set boot_modules {
	core init timer ps2_drv test-input acpi_drv pci_drv
}


build_boot_image $boot_modules

append qemu_args " -m 256 "


run_genode_until forever
